import { ArrowLeft, ArrowRight, Check, Command, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'

export function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const isRegister = mode === 'register'
  const [showPassword, setShowPassword] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', password: '' })
  const { login, register } = useApp()
  const navigate = useNavigate()
  const submit = (event: FormEvent) => { event.preventDefault(); isRegister ? register(form.name || 'Alex Morgan', form.email || 'alex.morgan@acme.co', form.password) : login(form.email, form.password); localStorage.setItem('taskflow-session', 'true'); navigate('/app/dashboard') }
  return <div className="auth-page"><div className="auth-art"><Link to="/" className="landing-brand"><span className="brand-mark"><Command size={17} /></span>taskflow</Link><div className="auth-quote"><div className="quote-mark">“</div><h2>Clarity is not a luxury.<br />It’s how good work gets done.</h2><p>— The TaskFlow principle</p></div><div className="auth-art-bottom"><span>✦</span><small>A workspace for your<br />most meaningful work.</small></div></div><div className="auth-panel"><Link to="/" className="back-link"><ArrowLeft size={15} /> Back to home</Link><div className="auth-form-wrap"><div className="auth-title"><span className="auth-icon">{isRegister ? <UserRound size={20} /> : <LockKeyhole size={20} />}</span><h1>{isRegister ? 'Create your workspace' : 'Welcome back'}</h1><p>{isRegister ? 'Start making space for meaningful work.' : 'Pick up where you left off.'}</p></div><form onSubmit={submit} className="form-stack">{isRegister && <label>Full name<div className="input-icon"><UserRound size={16} /><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Alex Morgan" /></div></label>}<label>Email address<div className="input-icon"><Mail size={16} /><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" /></div></label><label>Password<div className="input-icon"><LockKeyhole size={16} /><input required type={showPassword ? 'text' : 'password'} minLength={6} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="••••••••" /><button type="button" onClick={() => setShowPassword((current) => !current)}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>{!isRegister && <div className="form-helper"><label className="checkbox-label"><input type="checkbox" /> <span>Remember me</span></label><Link to="/login" className="small-link">Forgot password?</Link></div>}<button type="submit" className="button button-primary button-full">{isRegister ? 'Create account' : 'Log in'} <ArrowRight size={16} /></button></form>{isRegister && <div className="auth-perks"><div><Check size={14} /> Free forever for personal use</div><div><Check size={14} /> No credit card required</div></div>}<p className="auth-switch">{isRegister ? 'Already have an account?' : 'New to TaskFlow?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Create an account'}</Link></p></div></div></div>
}
