import { Bell, Check, ChevronRight, Moon, Shield, SlidersHorizontal, Sun } from 'lucide-react'
import { useState } from 'react'
import { useApp } from '../context/AppContext'

export function SettingsPage() {
  const { theme, toggleTheme, showToast } = useApp()
  const [notifications, setNotifications] = useState(true)
  const [weekly, setWeekly] = useState(true)
  return <div className="settings-page"><div className="page-heading"><div><span className="eyebrow">Make it yours</span><h1>Settings</h1><p>Shape TaskFlow around the way you work.</p></div></div><div className="settings-layout"><div className="settings-nav"><button className="active"><SlidersHorizontal size={16} /> Preferences</button><button onClick={() => showToast('Security settings are coming soon')}><Shield size={16} /> Security</button><button onClick={() => showToast('Notifications are ready to customize')}><Bell size={16} /> Notifications</button></div><div className="settings-sections"><section className="panel setting-section"><div className="setting-heading"><div><h2>Appearance</h2><p>Choose how TaskFlow feels across your workspace.</p></div><span className="setting-icon"><Sun size={17} /></span></div><div className="theme-options"><button className={theme === 'light' ? 'theme-option selected' : 'theme-option'} onClick={() => theme !== 'light' && toggleTheme()}><span className="theme-preview light-preview"><i /><i /><i /></span><span>Light</span>{theme === 'light' && <Check size={15} />}</button><button className={theme === 'dark' ? 'theme-option selected' : 'theme-option'} onClick={() => theme !== 'dark' && toggleTheme()}><span className="theme-preview dark-preview"><i /><i /><i /></span><span>Dark</span>{theme === 'dark' && <Check size={15} />}</button></div></section><section className="panel setting-section"><div className="setting-heading"><div><h2>Notifications</h2><p>Stay in the loop without losing your focus.</p></div><span className="setting-icon"><Bell size={17} /></span></div><div className="setting-row"><div><strong>Task updates</strong><span>Get notified when tasks are due or updated.</span></div><button className={`toggle ${notifications ? 'on' : ''}`} onClick={() => setNotifications((value) => !value)} aria-label="Toggle task updates"><i /></button></div><div className="setting-row"><div><strong>Weekly reflection</strong><span>Receive a gentle Monday summary of your momentum.</span></div><button className={`toggle ${weekly ? 'on' : ''}`} onClick={() => setWeekly((value) => !value)} aria-label="Toggle weekly reflection"><i /></button></div></section><section className="panel setting-section"><div className="setting-heading"><div><h2>Workspace</h2><p>Manage your workspace defaults.</p></div><span className="setting-icon"><Moon size={17} /></span></div><button className="setting-link" onClick={() => showToast('Workspace preferences saved')}><span>Default task view</span><span>List view <ChevronRight size={15} /></span></button><button className="setting-link" onClick={() => showToast('Week starts on Monday')}><span>Week starts on</span><span>Monday <ChevronRight size={15} /></span></button></section></div></div></div>
}
